### ISSUE TITLE
Commenting on what each line does

### ISSUE THREAD

**Issue by aceofpack** [robkorn/plutus-experimental-smart-contracts#1]
More of a suggestion than issue, but it would be awesome if you could comment what each line is doing and why in the context of the smart contract objective. Lots of comments can really help when it’s a learning piece of code 👍

**Comment by robkorn** [comment]
Thanks for the suggestion but as stated in the README these aren't meant to be tutorials for those who want line-by-line explanation, but instead they are aimed at the more motivated learner. Tutorials will come in due time (probably within a month) but until then I'm sure you can get a hang of it if you put in enough effort. The explanations in the files are already years ahead of clarifying how the Plutus Platform works compared to the bits of documentation in the source code.
